/// Built-in campaign packs ordered from foundational lessons to expert play.
enum Campaign {
    private static let foundationThemes: [Theme] = [
        Theme(name: "Los Colores", english: "Colours", emoji: "🎨", words: [
            .init(spanish: "rojo", english: "red"),
            .init(spanish: "azul", english: "blue"),
            .init(spanish: "verde", english: "green"),
            .init(spanish: "negro", english: "black"),
            .init(spanish: "blanco", english: "white"),
            .init(spanish: "amarillo", english: "yellow"),
            .init(spanish: "rosa", english: "pink"),
            .init(spanish: "gris", english: "grey"),
        ]),
        Theme(name: "Los Números", english: "Numbers", emoji: "🔢", words: [
            .init(spanish: "uno", english: "one"),
            .init(spanish: "dos", english: "two"),
            .init(spanish: "tres", english: "three"),
            .init(spanish: "cuatro", english: "four"),
            .init(spanish: "cinco", english: "five"),
            .init(spanish: "seis", english: "six"),
            .init(spanish: "siete", english: "seven"),
            .init(spanish: "ocho", english: "eight"),
        ]),
        Theme(name: "Los Animales", english: "Animals", emoji: "🐾", words: [
            .init(spanish: "gato", english: "cat"),
            .init(spanish: "perro", english: "dog"),
            .init(spanish: "pájaro", english: "bird"),
            .init(spanish: "pez", english: "fish"),
            .init(spanish: "caballo", english: "horse"),
            .init(spanish: "vaca", english: "cow"),
            .init(spanish: "ratón", english: "mouse"),
            .init(spanish: "oso", english: "bear"),
        ]),
        Theme(name: "La Comida", english: "Food", emoji: "🍎", words: [
            .init(spanish: "pan", english: "bread"),
            .init(spanish: "leche", english: "milk"),
            .init(spanish: "manzana", english: "apple"),
            .init(spanish: "queso", english: "cheese"),
            .init(spanish: "huevo", english: "egg"),
            .init(spanish: "carne", english: "meat"),
            .init(spanish: "arroz", english: "rice"),
            .init(spanish: "agua", english: "water"),
        ]),
        Theme(name: "La Familia", english: "Family", emoji: "👪", words: [
            .init(spanish: "madre", english: "mother"),
            .init(spanish: "padre", english: "father"),
            .init(spanish: "hermano", english: "brother"),
            .init(spanish: "hermana", english: "sister"),
            .init(spanish: "hijo", english: "son"),
            .init(spanish: "hija", english: "daughter"),
            .init(spanish: "abuelo", english: "grandfather"),
            .init(spanish: "esposa", english: "wife"),
        ]),
        Theme(name: "La Casa", english: "The House", emoji: "🏠", words: [
            .init(spanish: "puerta", english: "door"),
            .init(spanish: "ventana", english: "window"),
            .init(spanish: "cocina", english: "kitchen"),
            .init(spanish: "cama", english: "bed"),
            .init(spanish: "silla", english: "chair"),
            .init(spanish: "mesa", english: "table"),
            .init(spanish: "baño", english: "bathroom"),
            .init(spanish: "llave", english: "key"),
        ]),
        Theme(name: "El Cuerpo", english: "The Body", emoji: "🧍", words: [
            .init(spanish: "cabeza", english: "head"),
            .init(spanish: "mano", english: "hand"),
            .init(spanish: "pie", english: "foot"),
            .init(spanish: "ojo", english: "eye"),
            .init(spanish: "boca", english: "mouth"),
            .init(spanish: "nariz", english: "nose"),
            .init(spanish: "brazo", english: "arm"),
            .init(spanish: "pierna", english: "leg"),
        ]),
        Theme(name: "La Naturaleza", english: "Nature", emoji: "🌳", words: [
            .init(spanish: "árbol", english: "tree"),
            .init(spanish: "flor", english: "flower"),
            .init(spanish: "río", english: "river"),
            .init(spanish: "montaña", english: "mountain"),
            .init(spanish: "cielo", english: "sky"),
            .init(spanish: "playa", english: "beach"),
            .init(spanish: "bosque", english: "forest"),
            .init(spanish: "nube", english: "cloud"),
        ]),
        Theme(name: "El Tiempo", english: "Weather", emoji: "🌦️", words: [
            .init(spanish: "sol", english: "sun"),
            .init(spanish: "lluvia", english: "rain"),
            .init(spanish: "viento", english: "wind"),
            .init(spanish: "nieve", english: "snow"),
            .init(spanish: "calor", english: "heat"),
            .init(spanish: "frío", english: "cold"),
            .init(spanish: "tormenta", english: "storm"),
            .init(spanish: "niebla", english: "fog"),
        ]),
        Theme(name: "El Viaje", english: "Travel", emoji: "✈️", words: [
            .init(spanish: "avión", english: "plane"),
            .init(spanish: "tren", english: "train"),
            .init(spanish: "coche", english: "car"),
            .init(spanish: "calle", english: "street"),
            .init(spanish: "ciudad", english: "city"),
            .init(spanish: "mapa", english: "map"),
            .init(spanish: "billete", english: "ticket"),
            .init(spanish: "maleta", english: "suitcase"),
        ]),
        Theme(name: "Las Emociones", english: "Emotions", emoji: "😊", words: [
            .init(spanish: "feliz", english: "happy"),
            .init(spanish: "triste", english: "sad"),
            .init(spanish: "enojado", english: "angry"),
            .init(spanish: "cansado", english: "tired"),
            .init(spanish: "asustado", english: "scared"),
            .init(spanish: "orgulloso", english: "proud"),
            .init(spanish: "celoso", english: "jealous"),
            .init(spanish: "sorprendido", english: "surprised"),
        ]),
        Theme(name: "Los Verbos", english: "Verbs", emoji: "🏃", words: [
            .init(spanish: "correr", english: "to run"),
            .init(spanish: "comer", english: "to eat"),
            .init(spanish: "dormir", english: "to sleep"),
            .init(spanish: "hablar", english: "to speak"),
            .init(spanish: "escribir", english: "to write"),
            .init(spanish: "aprender", english: "to learn"),
            .init(spanish: "entender", english: "to understand"),
            .init(spanish: "trabajar", english: "to work"),
        ]),
    ]

    private static let masterMindThemes: [Theme] = [
        Theme(name: "La Argumentación", english: "Reasoned debate", emoji: "⚖️", words: [
            .init(spanish: "sin embargo", english: "however"),
            .init(spanish: "por lo tanto", english: "therefore"),
            .init(spanish: "aunque", english: "although"),
            .init(spanish: "sostener", english: "to maintain"),
            .init(spanish: "refutar", english: "to refute"),
            .init(spanish: "evidencia", english: "evidence"),
            .init(spanish: "premisa", english: "premise"),
            .init(spanish: "conclusión", english: "conclusion"),
        ]),
        Theme(name: "El Mundo Laboral", english: "Professional life", emoji: "💼", words: [
            .init(spanish: "plazo", english: "deadline"),
            .init(spanish: "presupuesto", english: "budget"),
            .init(spanish: "reunión", english: "meeting"),
            .init(spanish: "desempeño", english: "performance"),
            .init(spanish: "ascenso", english: "promotion"),
            .init(spanish: "plantilla", english: "workforce"),
            .init(spanish: "negociar", english: "to negotiate"),
            .init(spanish: "renunciar", english: "to resign"),
        ]),
        Theme(name: "La Sociedad", english: "Society and citizenship", emoji: "🏛️", words: [
            .init(spanish: "ciudadanía", english: "citizenship"),
            .init(spanish: "desigualdad", english: "inequality"),
            .init(spanish: "derechos", english: "rights"),
            .init(spanish: "deberes", english: "duties"),
            .init(spanish: "comunidad", english: "community"),
            .init(spanish: "justicia", english: "justice"),
            .init(spanish: "política", english: "politics"),
            .init(spanish: "bienestar", english: "well-being"),
        ]),
        Theme(name: "Ciencia y Tecnología", english: "Science and technology", emoji: "🔬", words: [
            .init(spanish: "hallazgo", english: "finding"),
            .init(spanish: "hipótesis", english: "hypothesis"),
            .init(spanish: "datos", english: "data"),
            .init(spanish: "sesgo", english: "bias"),
            .init(spanish: "algoritmo", english: "algorithm"),
            .init(spanish: "privacidad", english: "privacy"),
            .init(spanish: "avance", english: "breakthrough"),
            .init(spanish: "investigar", english: "to research"),
        ]),
        Theme(name: "Las Finanzas", english: "Personal finance", emoji: "📈", words: [
            .init(spanish: "ahorro", english: "savings"),
            .init(spanish: "deuda", english: "debt"),
            .init(spanish: "interés", english: "interest"),
            .init(spanish: "ingresos", english: "income"),
            .init(spanish: "gastos", english: "expenses"),
            .init(spanish: "inversión", english: "investment"),
            .init(spanish: "préstamo", english: "loan"),
            .init(spanish: "riesgo", english: "risk"),
        ]),
        Theme(name: "La Literatura", english: "Literary analysis", emoji: "📖", words: [
            .init(spanish: "trama", english: "plot"),
            .init(spanish: "narrador", english: "narrator"),
            .init(spanish: "metáfora", english: "metaphor"),
            .init(spanish: "desenlace", english: "resolution"),
            .init(spanish: "personaje", english: "character"),
            .init(spanish: "ensayo", english: "essay"),
            .init(spanish: "verso", english: "verse"),
            .init(spanish: "borrador", english: "draft"),
        ]),
        Theme(name: "La Filosofía", english: "Philosophy", emoji: "🧠", words: [
            .init(spanish: "conciencia", english: "consciousness"),
            .init(spanish: "verdad", english: "truth"),
            .init(spanish: "duda", english: "doubt"),
            .init(spanish: "libertad", english: "freedom"),
            .init(spanish: "ética", english: "ethics"),
            .init(spanish: "propósito", english: "purpose"),
            .init(spanish: "conocimiento", english: "knowledge"),
            .init(spanish: "existencia", english: "existence"),
        ]),
        Theme(name: "Los Modismos", english: "Idiomatic expressions", emoji: "🧩", words: [
            .init(spanish: "darse cuenta", english: "to realise"),
            .init(spanish: "echar de menos", english: "to miss"),
            .init(spanish: "tener en cuenta", english: "to bear in mind"),
            .init(spanish: "llevar a cabo", english: "to carry out"),
            .init(spanish: "estar de acuerdo", english: "to agree"),
            .init(spanish: "a pesar de", english: "despite"),
            .init(spanish: "por si acaso", english: "just in case"),
            .init(spanish: "de vez en cuando", english: "from time to time"),
        ]),
    ]

    static let packs: [CampaignPack] = [
        CampaignPack(
            id: "foundations",
            title: "Primeros Pasos",
            subtitle: "Build confidence across 12 storybook adventures",
            emoji: "🗺️",
            firstLevelIndex: 0,
            themes: foundationThemes
        ),
        CampaignPack(
            id: "master-minds",
            title: "Mentes Maestras",
            subtitle: "Expert vocabulary, precision routes, and mechanic puzzles",
            emoji: "🧠",
            firstLevelIndex: foundationThemes.count,
            themes: masterMindThemes
        ),
    ]

    static let themes = packs.flatMap(\.themes)
    static let wordCount = themes.flatMap(\.words).count
}
